# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Device-WS2500PC
version:      0.99
version_from: lib/Device/WS2500PC.pm
installdirs:  site
requires:
    Device::SerialPort:            0
    Time::HiRes:                   0
    Time::Local:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
